root: true
parser: '@typescript-eslint/parser'
parserOptions:
    project:
        - './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - react
    - react-native
    - jest
    - simple-import-sort
extends:
    - '@react-native-community'
    - eslint:all
    - plugin:@typescript-eslint/all
    - plugin:react/all
    - plugin:react/jsx-runtime
    - plugin:react-native/all
    - plugin:jest/all
    - prettier
rules:
    '@typescript-eslint/naming-convention': 0
    sort-imports: 0 # We already use the simple-import-sort plugin
    one-var: 0
    "@typescript-eslint/require-await": 0
    "@typescript-eslint/prefer-readonly-parameter-types": 0
    "@typescript-eslint/no-floating-promises": 0
