root: true
parser: '@typescript-eslint/parser'
parserOptions:
    project:
        - './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - react
    - react-native
    - jest
    - simple-import-sort
extends:
    - '@react-native-community'
    - eslint:all
    - plugin:@typescript-eslint/all
    - plugin:react/all
    - plugin:react/jsx-runtime
    - plugin:react-native/all
    - plugin:jest/all
    - prettier
rules:
    "@typescript-eslint/naming-convention": 0
